[package]
name = "segvec"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[dev-dependencies]
proptest = "1"
criterion = "0.3.5"

[[bench]]
name = "grow"
harness = false